# Generated by Django 5.2.1 on 2026-04-28 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('ppt', 'PPT'), ('video', 'Video'), ('topic_manual', 'Topic Manual')], max_length=16)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('topic_name', models.CharField(blank=True, max_length=150, null=True)),
                ('subtopics', models.JSONField(default=list)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('questions_generated', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_contents', to='users.examifyuser')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
