# Generated by Django 5.2.1 on 2026-04-28 19:18

import django.core.validators
import django.db.models.deletion
import quiz.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exam_target', models.CharField(choices=[('JEE', 'JEE'), ('NEET', 'NEET'), ('UPSC', 'UPSC'), ('GATE', 'GATE'), ('CAT', 'CAT'), ('GRE', 'GRE'), ('GMAT', 'GMAT'), ('SAT', 'SAT'), ('LSAT', 'LSAT'), ('MCAT', 'MCAT'), ('IELTS', 'IELTS'), ('TOEFL', 'TOEFL'), ('CFA', 'CFA'), ('CA_Foundation', 'CA_Foundation'), ('SSC_CGL', 'SSC_CGL'), ('NDA', 'NDA'), ('CLAT', 'CLAT'), ('CUET', 'CUET'), ('IAS', 'IAS'), ('Bar_Exam', 'Bar_Exam')], max_length=32)),
                ('subject', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=150)),
                ('subtopic', models.CharField(blank=True, max_length=150, null=True)),
                ('difficulty', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(1.0)])),
                ('q_type', models.CharField(choices=[('MCQ', 'MCQ'), ('Numerical', 'Numerical'), ('Assertion', 'Assertion'), ('Match', 'Match')], max_length=16)),
                ('question_text', models.TextField()),
                ('options', models.JSONField(validators=[quiz.models.validate_four_options])),
                ('correct_answer', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('explanation', models.TextField()),
                ('source_type', models.CharField(choices=[('ai_generated', 'AI Generated'), ('content_extracted', 'Content Extracted')], max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('free_quiz', 'Free Quiz'), ('daily_plan', 'Daily Plan'), ('diagnostic', 'Diagnostic'), ('topic_practice', 'Topic Practice')], max_length=20)),
                ('exam_target', models.CharField(choices=[('JEE', 'JEE'), ('NEET', 'NEET'), ('UPSC', 'UPSC'), ('GATE', 'GATE'), ('CAT', 'CAT'), ('GRE', 'GRE'), ('GMAT', 'GMAT'), ('SAT', 'SAT'), ('LSAT', 'LSAT'), ('MCAT', 'MCAT'), ('IELTS', 'IELTS'), ('TOEFL', 'TOEFL'), ('CFA', 'CFA'), ('CA_Foundation', 'CA_Foundation'), ('SSC_CGL', 'SSC_CGL'), ('NDA', 'NDA'), ('CLAT', 'CLAT'), ('CUET', 'CUET'), ('IAS', 'IAS'), ('Bar_Exam', 'Bar_Exam')], max_length=32)),
                ('questions', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score_pct', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('xp_earned', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_sessions', to='users.examifyuser')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('is_correct', models.BooleanField()),
                ('response_time', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('failure_type', models.CharField(choices=[('conceptual', 'Conceptual'), ('silly', 'Silly'), ('time', 'Time'), ('recall', 'Recall'), ('correct', 'Correct')], max_length=16)),
                ('xp_delta', models.IntegerField(default=0)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_answers', to='quiz.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.quizsession')),
            ],
            options={
                'ordering': ['answered_at'],
                'constraints': [models.UniqueConstraint(fields=('session', 'question'), name='uniq_session_question_answer')],
            },
        ),
    ]
