# Generated by Django 6.0.4 on 2026-04-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_question_exam_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizsession',
            name='session_type',
            field=models.CharField(choices=[('free_quiz', 'Free Quiz'), ('daily_plan', 'Daily Plan'), ('diagnostic', 'Diagnostic'), ('topic_practice', 'Topic Practice'), ('content_quiz', 'Content Quiz')], max_length=20),
        ),
    ]
