# Generated by Django 5.2.1 on 2026-05-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_quizsession_session_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi'), ('hinglish', 'Hinglish')], default='english', max_length=15),
        ),
    ]
