# Generated by Django 5.2.1 on 2026-04-28 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamifyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clerk_id', models.CharField(max_length=128, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('exam_target', models.CharField(choices=[('JEE', 'JEE'), ('NEET', 'NEET'), ('UPSC', 'UPSC'), ('GATE', 'GATE'), ('CAT', 'CAT'), ('GRE', 'GRE'), ('GMAT', 'GMAT'), ('SAT', 'SAT'), ('LSAT', 'LSAT'), ('MCAT', 'MCAT'), ('IELTS', 'IELTS'), ('TOEFL', 'TOEFL'), ('CFA', 'CFA'), ('CA_Foundation', 'CA_Foundation'), ('SSC_CGL', 'SSC_CGL'), ('NDA', 'NDA'), ('CLAT', 'CLAT'), ('CUET', 'CUET'), ('IAS', 'IAS'), ('Bar_Exam', 'Bar_Exam')], max_length=32)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('premium', 'Premium')], default='free', max_length=10)),
                ('plan_expiry', models.DateTimeField(blank=True, null=True)),
                ('credits_remaining', models.IntegerField(default=3, help_text='free=3 quizzes ever, pro=1500, premium=unlimited')),
                ('xp', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('streak', models.IntegerField(default=0)),
                ('last_active', models.DateField(blank=True, null=True)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_target', models.CharField(choices=[('JEE', 'JEE'), ('NEET', 'NEET'), ('UPSC', 'UPSC'), ('GATE', 'GATE'), ('CAT', 'CAT'), ('GRE', 'GRE'), ('GMAT', 'GMAT'), ('SAT', 'SAT'), ('LSAT', 'LSAT'), ('MCAT', 'MCAT'), ('IELTS', 'IELTS'), ('TOEFL', 'TOEFL'), ('CFA', 'CFA'), ('CA_Foundation', 'CA_Foundation'), ('SSC_CGL', 'SSC_CGL'), ('NDA', 'NDA'), ('CLAT', 'CLAT'), ('CUET', 'CUET'), ('IAS', 'IAS'), ('Bar_Exam', 'Bar_Exam')], max_length=32)),
                ('rank', models.IntegerField(default=0)),
                ('xp_this_week', models.IntegerField(default=0)),
                ('xp_all_time', models.IntegerField(default=0)),
                ('week_start', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='users.examifyuser')),
            ],
            options={
                'ordering': ['rank', '-xp_this_week'],
                'constraints': [models.UniqueConstraint(fields=('user', 'exam_target', 'week_start'), name='uniq_user_exam_week_start')],
            },
        ),
        migrations.CreateModel(
            name='TopicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=100)),
                ('exam_target', models.CharField(choices=[('JEE', 'JEE'), ('NEET', 'NEET'), ('UPSC', 'UPSC'), ('GATE', 'GATE'), ('CAT', 'CAT'), ('GRE', 'GRE'), ('GMAT', 'GMAT'), ('SAT', 'SAT'), ('LSAT', 'LSAT'), ('MCAT', 'MCAT'), ('IELTS', 'IELTS'), ('TOEFL', 'TOEFL'), ('CFA', 'CFA'), ('CA_Foundation', 'CA_Foundation'), ('SSC_CGL', 'SSC_CGL'), ('NDA', 'NDA'), ('CLAT', 'CLAT'), ('CUET', 'CUET'), ('IAS', 'IAS'), ('Bar_Exam', 'Bar_Exam')], max_length=32)),
                ('ability_score', models.FloatField(default=0.5)),
                ('stars', models.IntegerField(default=0)),
                ('is_unlocked', models.BooleanField(default=False)),
                ('is_flagged_complete', models.BooleanField(default=False)),
                ('failure_dna', models.JSONField(default=dict)),
                ('total_attempts', models.IntegerField(default=0)),
                ('correct_count', models.IntegerField(default=0)),
                ('accuracy_pct', models.FloatField(default=0.0)),
                ('next_review', models.DateTimeField(blank=True, null=True)),
                ('correct_streak', models.IntegerField(default=0)),
                ('graph_position_x', models.IntegerField(default=0)),
                ('graph_position_y', models.IntegerField(default=0)),
                ('prerequisite_topics', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_profiles', to='users.examifyuser')),
            ],
            options={
                'ordering': ['subject', 'topic_name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'topic_name', 'exam_target'), name='uniq_user_topic_exam_target')],
            },
        ),
    ]
