# Generated by Django 5.2.1 on 2026-04-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examifyuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='examifyuser',
            name='exam_target',
            field=models.CharField(choices=[('JEE_Mains', 'JEE_Mains'), ('JEE_Advanced', 'JEE_Advanced'), ('NEET', 'NEET'), ('UPSC_CSE', 'UPSC_CSE'), ('UPSC_IFS', 'UPSC_IFS'), ('GATE', 'GATE'), ('CAT', 'CAT'), ('XAT', 'XAT'), ('MAT', 'MAT'), ('GMAT', 'GMAT'), ('GRE', 'GRE'), ('SAT', 'SAT'), ('ACT', 'ACT'), ('LSAT', 'LSAT'), ('MCAT', 'MCAT'), ('IELTS', 'IELTS'), ('TOEFL', 'TOEFL'), ('CFA_L1', 'CFA_L1'), ('CFA_L2', 'CFA_L2'), ('CFA_L3', 'CFA_L3'), ('CA_Foundation', 'CA_Foundation'), ('CA_Intermediate', 'CA_Intermediate'), ('CA_Final', 'CA_Final'), ('SSC_CGL', 'SSC_CGL'), ('SSC_CHSL', 'SSC_CHSL'), ('NDA', 'NDA'), ('CDS', 'CDS'), ('CLAT', 'CLAT'), ('AILET', 'AILET'), ('CUET', 'CUET'), ('SNAP', 'SNAP'), ('IIFT', 'IIFT'), ('CMAT', 'CMAT'), ('NMAT', 'NMAT'), ('BAR_EXAM_US', 'BAR_EXAM_US'), ('BAR_EXAM_UK', 'BAR_EXAM_UK'), ('ACCA', 'ACCA'), ('CPA_US', 'CPA_US')], max_length=32),
        ),
        migrations.AlterField(
            model_name='leaderboardentry',
            name='exam_target',
            field=models.CharField(choices=[('JEE_Mains', 'JEE_Mains'), ('JEE_Advanced', 'JEE_Advanced'), ('NEET', 'NEET'), ('UPSC_CSE', 'UPSC_CSE'), ('UPSC_IFS', 'UPSC_IFS'), ('GATE', 'GATE'), ('CAT', 'CAT'), ('XAT', 'XAT'), ('MAT', 'MAT'), ('GMAT', 'GMAT'), ('GRE', 'GRE'), ('SAT', 'SAT'), ('ACT', 'ACT'), ('LSAT', 'LSAT'), ('MCAT', 'MCAT'), ('IELTS', 'IELTS'), ('TOEFL', 'TOEFL'), ('CFA_L1', 'CFA_L1'), ('CFA_L2', 'CFA_L2'), ('CFA_L3', 'CFA_L3'), ('CA_Foundation', 'CA_Foundation'), ('CA_Intermediate', 'CA_Intermediate'), ('CA_Final', 'CA_Final'), ('SSC_CGL', 'SSC_CGL'), ('SSC_CHSL', 'SSC_CHSL'), ('NDA', 'NDA'), ('CDS', 'CDS'), ('CLAT', 'CLAT'), ('AILET', 'AILET'), ('CUET', 'CUET'), ('SNAP', 'SNAP'), ('IIFT', 'IIFT'), ('CMAT', 'CMAT'), ('NMAT', 'NMAT'), ('BAR_EXAM_US', 'BAR_EXAM_US'), ('BAR_EXAM_UK', 'BAR_EXAM_UK'), ('ACCA', 'ACCA'), ('CPA_US', 'CPA_US')], max_length=32),
        ),
        migrations.AlterField(
            model_name='topicprofile',
            name='exam_target',
            field=models.CharField(choices=[('JEE_Mains', 'JEE_Mains'), ('JEE_Advanced', 'JEE_Advanced'), ('NEET', 'NEET'), ('UPSC_CSE', 'UPSC_CSE'), ('UPSC_IFS', 'UPSC_IFS'), ('GATE', 'GATE'), ('CAT', 'CAT'), ('XAT', 'XAT'), ('MAT', 'MAT'), ('GMAT', 'GMAT'), ('GRE', 'GRE'), ('SAT', 'SAT'), ('ACT', 'ACT'), ('LSAT', 'LSAT'), ('MCAT', 'MCAT'), ('IELTS', 'IELTS'), ('TOEFL', 'TOEFL'), ('CFA_L1', 'CFA_L1'), ('CFA_L2', 'CFA_L2'), ('CFA_L3', 'CFA_L3'), ('CA_Foundation', 'CA_Foundation'), ('CA_Intermediate', 'CA_Intermediate'), ('CA_Final', 'CA_Final'), ('SSC_CGL', 'SSC_CGL'), ('SSC_CHSL', 'SSC_CHSL'), ('NDA', 'NDA'), ('CDS', 'CDS'), ('CLAT', 'CLAT'), ('AILET', 'AILET'), ('CUET', 'CUET'), ('SNAP', 'SNAP'), ('IIFT', 'IIFT'), ('CMAT', 'CMAT'), ('NMAT', 'NMAT'), ('BAR_EXAM_US', 'BAR_EXAM_US'), ('BAR_EXAM_UK', 'BAR_EXAM_UK'), ('ACCA', 'ACCA'), ('CPA_US', 'CPA_US')], max_length=32),
        ),
    ]
