# Generated by Django 5.2.1 on 2026-04-28 22:13

from django.db import migrations, models
from django.utils import timezone


def mark_existing_users_onboarded(apps, schema_editor):
    ExamifyUser = apps.get_model("users", "ExamifyUser")
    ExamifyUser.objects.filter(onboarding_completed=False).update(
        onboarding_completed=True,
        onboarding_completed_at=timezone.now(),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_examifyuser_is_active_alter_examifyuser_exam_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examifyuser',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examifyuser',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(mark_existing_users_onboarded, migrations.RunPython.noop),
    ]
