# Generated by Django 6.0.4 on 2026-04-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_examifyuser_onboarding_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examifyuser',
            name='credits_remaining',
            field=models.IntegerField(default=30, help_text='free=30 (3 quizzes × 10), pro=1500, premium=unlimited (-1)'),
        ),
    ]
