# Generated by Django 6.0.4 on 2026-04-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_examifyuser_credits_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='examifyuser',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
