# Generated by Django 5.2.1 on 2026-05-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_examifyuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='examifyuser',
            name='language',
            field=models.CharField(choices=[('english', 'English Medium'), ('hindi', 'Hindi Medium'), ('hinglish', 'Hinglish Mix')], default='hinglish', max_length=15),
        ),
    ]
