# Generated by Django 5.2.1 on 2026-04-28 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('pro', 'Pro'), ('premium', 'Premium')], max_length=10)),
                ('duration_months', models.PositiveSmallIntegerField(choices=[(1, '1'), (3, '3'), (6, '6')])),
                ('credits_granted', models.IntegerField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_id', models.CharField(max_length=128)),
                ('started_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_transactions', to='users.examifyuser')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
