# Generated by Django 5.2.1 on 2026-04-29 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_examifyuser_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumPlanSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_target', models.CharField(choices=[('JEE_Mains', 'JEE_Mains'), ('JEE_Advanced', 'JEE_Advanced'), ('NEET', 'NEET'), ('UPSC_CSE', 'UPSC_CSE'), ('UPSC_IFS', 'UPSC_IFS'), ('GATE', 'GATE'), ('CAT', 'CAT'), ('XAT', 'XAT'), ('MAT', 'MAT'), ('GMAT', 'GMAT'), ('GRE', 'GRE'), ('SAT', 'SAT'), ('ACT', 'ACT'), ('LSAT', 'LSAT'), ('MCAT', 'MCAT'), ('IELTS', 'IELTS'), ('TOEFL', 'TOEFL'), ('CFA_L1', 'CFA_L1'), ('CFA_L2', 'CFA_L2'), ('CFA_L3', 'CFA_L3'), ('CA_Foundation', 'CA_Foundation'), ('CA_Intermediate', 'CA_Intermediate'), ('CA_Final', 'CA_Final'), ('SSC_CGL', 'SSC_CGL'), ('SSC_CHSL', 'SSC_CHSL'), ('NDA', 'NDA'), ('CDS', 'CDS'), ('CLAT', 'CLAT'), ('AILET', 'AILET'), ('CUET', 'CUET'), ('SNAP', 'SNAP'), ('IIFT', 'IIFT'), ('CMAT', 'CMAT'), ('NMAT', 'NMAT'), ('BAR_EXAM_US', 'BAR_EXAM_US'), ('BAR_EXAM_UK', 'BAR_EXAM_UK'), ('ACCA', 'ACCA'), ('CPA_US', 'CPA_US')], max_length=32)),
                ('status', models.CharField(choices=[('fresh', 'Fresh'), ('stale', 'Stale'), ('failed', 'Failed')], default='stale', max_length=10)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('source_completed_sessions', models.PositiveIntegerField(default=0)),
                ('source_answers_count', models.PositiveIntegerField(default=0)),
                ('plan_payload', models.JSONField(default=dict)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_plan_snapshots', to='users.examifyuser')),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'exam_target'), name='uniq_premium_plan_snapshot_user_exam')],
            },
        ),
    ]
